---
title: "MCM G1 Nanoparticles PrestoBlue Assay"
output:
  html_document:
    df_print: paged
---


```{r setup}
path <- "20230428_Nanoparticles_OD1_24h_reduced.xls"

library(tidyverse)
library(magrittr)
library(stringr)
library(readr)
library(knitr)
library(xlsx)
```


```{r read_data}
data <- read_file(path, locale = locale(encoding = "UTF-16LE"))

plates <- 
  str_match_all(data, "Plate:.*\\R[\t\\d]*\\R(\t[\\s\\d]*\\R)*~End")[[1]][,2] %>%
  as.list()

names(plates) <- str_match_all(data, "Plate:\t(.*?)\t")[[1]][,2]

plates <- 
  lapply(plates, . %>% 
           str_split_1("\\R") %>%
           str_sub(start = 3, end = -2) %>%
           read.delim(text = ., header = F, sep = "\t") %>%
           as_tibble() %>%
           rename_with(function(x) {as.character(seq(ncol(.)))}) %>%
           add_column(Row = seq(nrow(.)), .before = "1") %>%
           pivot_longer(!Row, names_to = "Col", names_transform = as.integer) %>%
           add_column(Well = paste0(LETTERS[.$Row], as.character(.$Col)), .before = "Row")
         )

data <- bind_rows(plates, .id = "Plate")
```


```{r}

limits <- c(min(data$value, na.rm=T), max(data$value, na.rm=T))
for (plate in names(plates)) {
  p <- data %>%
    filter(Plate == plate) %>%
    ggplot(aes(x=Col, y=Row, fill=value)) + 
      geom_point(shape=21, size=12, stroke=1.5) +
      geom_text(aes(label=formatC(value, format = "E", digits = 2)), size=2) +
      coord_fixed() + 
      scale_y_reverse(breaks = seq(8), 
                      labels = LETTERS[1:8], 
                      expand = expansion(add = 0.75)) + 
      scale_x_continuous(breaks = seq(12), 
                         expand = expansion(add = 0.75)) + 
      scale_fill_continuous(limits = limits, type = "viridis") + 
      labs(x = "", y = "") + 
      ggtitle(plate) +
      theme_bw() +
      theme(panel.grid = element_blank(), axis.ticks = element_blank())
    print(p)
}

```

```{r}
append <- F
for (name in names(plates)) {
  plate <- plates[[name]]
  out <- matrix("X", ncol = plate$Col[nrow(plate)], nrow = plate$Row[nrow(plate)])
  colnames(out) <- as.character(seq(12))
  rownames(out) <- LETTERS[seq(8)]
  write.xlsx(out, "plate_mask.xlsx", sheetName = name, col.names = F, row.names = F, append = append)
  append <- T
}
```

```{r}
masks <- list()
for (name in names(plates)) {
  masks <- append(masks, list(read.xlsx("plate_mask_NPs.xlsx", sheetName = name, header = F)))
}

names(masks) <- names(plates)
masks <- lapply(masks, . %>%
                  mutate(across(everything(), ~ na_if(.x, "X"))) %>%
                  as_tibble() %>%
                  rename_with(function(x) {as.character(seq(ncol(.)))}) %>%
                  add_column(Row = seq(nrow(.)), .before = "1") %>%
                  pivot_longer(!Row, names_to = "Col", names_transform = as.integer, values_to = "Type") %>%
                  add_column(Well = paste0(LETTERS[.$Row], as.character(.$Col)), .before = "Row")
                ) %>%
  bind_rows(.id = "Plate")
```

```{r}
data <- full_join(masks, data, by = c("Plate", "Well", "Row", "Col")) %>%
  drop_na() %>%
  separate_wider_regex(Type, 
                       c(Type = "\\w*", "\\(", Concentration = "\\d*\\.?\\d*", "\\)"), 
                       too_few = "align_start") %>%
  mutate(Row = NULL, Col = NULL, Concentration = as.numeric(Concentration))
```


```{r}
data %>% 
  group_by(Plate) %T>%
  {print(paste("Medium Blank:", 
               round(mean(.$value[.$Type == "MB"])), 
               "\U00B1",
               round(sd(.$value[.$Type == "MB"]))))} %>% 
  mutate(value = value - mean(value[Type == "MB"])) %>%
  filter(Type != "MB") %T>%
  {print(paste("Treatment Blank:", 
               round(mean(.$value[.$Type == "TB"])), 
               "\U00B1",
               round(sd(.$value[.$Type == "TB"]))))} %>% 
  mutate(value = value / mean(value[Type == "TB"])) %>%
  filter(Type != "TB") %>%
  ungroup() %>%
  ggplot(aes(x=Concentration, y=value, group=Type, col=Type)) + 
    geom_line(stat = "summary", fun = mean) + 
    scale_x_log10()
```

